[build]
builder = "dockerfile"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[deploy.railway]
DATABASE_URL = "${RAILWAY_POSTGRESQL_CONNECTION_URL}" 