[build]
builder = "nixpacks"
buildCommand = "npm ci --cache /tmp/npm-cache --no-audit --no-fund && npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[deploy.railway]
DATABASE_URL = "${RAILWAY_POSTGRESQL_CONNECTION_URL}" 